version: '3'

services:
  webapp:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - LOG_LEVEL=INFO
      - SERVER_ADDRESS=0.0.0.0:8080
      - ENABLE_CACHE=true
      - CACHE_TYPE=MEMCACHE
      - MEMCACHE_ADDRESS=memcached:11211
      - STORAGE_TYPE=PEBBLE
      - DB_HOST=postgres:5432
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_NAME=postgres
    depends_on:
      - postgres
      - memcached

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

  memcached:
    image: memcached:latest
    ports:
      - "11211:11211"
