{
 "title": "Gin Application Monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "PV Rate",
   "type": "gauge",
   "description": "Application request rate every 5 minutes.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "rate(gin_request_total[5m])" }
   ]
  },
  {
   "title": "PV",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "gin_request_total", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "UV",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "gin_request_uv_total", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Traffic In-Out",
   "type": "graph",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(gin_request_body_total[5m])",
     "legendFormat": "{{instance}}-in"
    },
    {
     "expr": "rate(gin_response_body_total[5m])",
     "legendFormat": "{{instance}}-out"
    }
   ]
  },
  {
   "title": "Status Code",
   "type": "table",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "gin_request_status_total" }
   ]
  }
 ]
}