jobs:
  golangci:
    runs-on: ubuntu-latest
    steps:
      # Config options can be found in README here: https://github.com/golangci/golangci-lint-action
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20.7'
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.52.2