name: go tests
on:
  pull_request:
  push:
    branches:
      - main*
jobs:
  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20.7'
      - uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - run: go test -coverprofile=coverage.out -covermode=atomic -timeout=5m -race ./...

  fuzz_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2 # For compose to build images
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20.7'
      - uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - run: go test -race -v -fuzzer -timeout=45m -log-dir=.
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: fuzz-test-logs
          path: testutil/compose/fuzz/*.log
          retention-days: 3